#!/bin/sh
#shortcut git status
#~zach

source ks_config.sh
source telhub.sh

i=0
for R in "${!REPO_SERVICE[@]}"
do
    cd ${MAIN_DIR}/${R}
    git reset --hard
    git checkout development
    git pull
    build_pod --dir=$R
done
