#!/bin/sh
# ~z

source ks_config.sh

if [ -z "$1" ]; then
    CREATE_REPLACE="replace"
else
    CREATE_REPLACE=$1
fi

if [ $CREATE_REPLACE == 'create' ]; then
    kubectl create namespace $NAMESPACE
    kubectl config set-context $CONTEXT --user=$KUBEUSR --namespace=$NAMESPACE --cluster=$CLUSTER
fi

kubectl $CREATE_REPLACE -f "${DEVOPS}/${NAMESPACE}/secrets/"
kubectl $CREATE_REPLACE -f "${DEVOPS}/${NAMESPACE}/configs/"
