#!/bin/bash
#shortcut to docker
#~zach

FULL=$(pwd)
DIR=$(basename "$FULL")

if [ -z "$2" ]; then
    PORT=4000
else
    PORT=$2
fi

if [ "$1" == 'build' ]; then
    docker build --tag=${DIR} .
elif [ "$1" == 'buildw' ]; then
    winpty docker build --tag=${DIR} .
elif [ "$1" == 'r' ] || [ "$1" == 'run' ]; then
    docker run -d -p $PORT:80 ${DIR}
elif [ "$1" == 'rw' ]; then
    winpty docker run -d -p $PORT:80 ${DIR}
elif [ "$1" == 'l' ] || [ "$1" == 'logs' ]; then
    docker logs ${DIR}
elif [ "$1" == 'push' ]; then
    docker push ${DIR}
elif [ "$1" == 'b' ]; then
    CON=$(docker ps -aqf "ancestor=${DIR}" -n 1)
    docker exec -it ${CON} /bin/bash
elif [ "$1" == 'bw' ]; then
    CON=$(docker ps -aqf "ancestor=${DIR}" -n 1)
    winpty docker exec -it ${CON} //bin/bash
elif [ "$1" == 'root' ]; then
    CON=$(docker ps -aqf "ancestor=${DIR}" -n 1)
    docker exec -it --user root ${CON} /bin/bash
elif [ "$1" == 'rootw' ]; then
    CON=$(docker ps -aqf "ancestor=${DIR}" -n 1)
    winpty docker exec -it --user root ${CON} //bin/bash
elif [ "$1" == 'p' ] || [ "$1" == 'prune' ]; then
    docker system prune -f -a
elif [ "$1" == 'ls' ]; then
    docker container ls -a
elif [ "$1" == 'i' ]; then
    docker ps -aqf "ancestor=${DIR}" -n 1
elif [ "$1" == 'kill' ]; then
    docker kill $(docker ps -q)
elif [ "$1" == 'rmi' ]; then
    docker rmi -f $(docker images -q)
fi
