#!/bin/bash
# ~z

CONTEXT=$(kubectl config current-context)
echo "Current Context: $CONTEXT"

if [ "$1" == "k" ]; then
        kontext
        kubectl get pods
elif [ "$1" == "a" ]; then
        kubectl get pods --all-namespaces
elif [ "$1" == "s" ]; then
        kubectl get services
elif [ "$1" == "h" ]; then
        kubectl get hpa
elif [ "$1" == "dh" ]; then
        kubectl describe hpa
elif [ "$1" == "dc" ]; then
        kubectl describe configmaps
elif [ "$1" == "d" ]; then
        kubectl get deployments -o custom-columns=":metadata.name"
elif [ "$1" == "dall" ]; then
    for N in $(kubectl get deployments -o custom-columns=":metadata.name")
    do
        kubectl delete deployment $N
    done
elif [ "$1" == "sall" ]; then
    for N in $(kubectl get services -o custom-columns=":metadata.name")
    do
        kubectl delete services $N
    done
else
        kubectl get pods $*
fi
