#!/bin/sh
# ~z

CONTEXTS=(`kubectl config get-contexts -o name`)


if [ ! -z "$1" ]; then
    kubectl config use-context $CONTEXTS[$1]
    exit
fi

select context in "${CONTEXTS[@]}"
do
       echo $context;
       kubectl config use-context $context;
       exit;
done
