#!/bin/sh
# ~z

source config.sh

select context in 'dev-telhub' 'uat-telhub' 'prf-telhub' 'prd-telhub' "$CONTEXT"
do
       echo $context;
       kubectl config use-context $context;
       exit;
done
