#!/bin/bash
# ~z


if [ "$1" == "k" ]; then
        kontext
fi

case "$1" in
    scale|hpa)
        PODS=$(kubectl get deployments -o custom-columns=":metadata.name")
        ;;
    *)
        PODS=$(kubectl get pods -o custom-columns=":metadata.name")
        ;;
esac


CONTEXT=$(kubectl config current-context)
echo "Current Context: $CONTEXT"

select pod in $PODS
do
        echo $pod;
        name=$(echo $pod | sed -re 's/-[^-]+-[^-]+$//')

        if [ "$1" == "describe" ] || [ "$1" == "d" ]; then
                kubectl describe pod $pod;
        elif [ "$1" == "logs" ]; then
                con=$(echo $pod | sed -re 's/-[^-]+-[^-]+$/-con/')
                kubectl logs $pod -c $con;
        elif [ "$1" == "log" ]; then
                kubectl logs -p  $pod
        elif [ "$1" == "laravel-logs" ]; then
                kubectl logs $pod -c laravel-logs;
        elif [ "$1" == "cp" ]; then
                kubectl cp $pod:$2 $3;
        elif [ "$1" == "scale" ]; then
                kubectl scale --replicas=$2 deployment/$pod
        elif [ "$1" == "dh" ]; then
                kubectl describe hpa $pod
        elif [ "$1" == "root" ]; then
                ##requires https://github.com/mikelorant/kubectl-exec-user
                kubectl plugin exec-user -u 0 $pod bash
        else
                kubectl exec -it $pod bash;
        fi
        exit;
done
