#!/bin/sh
#shortcut git status
#~zach

source telhub.sh

for r in "${REPO[@]}"
do
    if [ $r == 'alpine-sqs' ]; then
        git clone https://github.com/roribio/alpine-sqs.git
    else
        git clone git@github.com:schneidertech/telematics-hub-${r}.git ${r}
    fi
done
