#!/bin/sh
#shortcut git status
#~zach

BASH_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source $BASH_DIR/ks_config.sh
source $BASH_DIR/telhub.sh

if [ ! -d $MAIN_DIR ]; then
    mkdir $MAIN_DIR
fi

cd $CHARTS

## create new helm chart from heartbeat
helm_chart(){
    if [ ! -d $1 ]; then
        cp -r heartbeat-ps-adapter $1
        for file in 'values.yaml' 'Chart.yaml' 'templates/_helpers.tpl' 'templates/ingress.yaml' 'templates/NOTES.txt'
        do
            sed -i "s/heartbeat-ps-adapter/$1/g" $1/${file}.yaml
        done
    fi
}

## update deployment file
cp_file(){
    cp heartbeat-ps-adapter/templates/${2}.yaml ${1}/templates/${2}.yaml
}

FILE='deployment'

if [ ! -z "$2" ]; then
    FILE=$2
fi

i=1

if [ "$1" == "all" ]; then
    for s in "${SERVICE[@]}"
    do
        if [ -z "${SKIP[$i]}" ]; then
            helm_chart $s
        fi
        let i++
    done
elif [ "$1" == "f" ]; then
    for s in "${SERVICE[@]}"
    do
        if [ -z "${SKIP[$i]}" ]; then
            cp_file $s $FILE
        fi
        let i++
    done
else
    select s in "${SERVICE[@]}"
    do
        helm_chart $s
        exit
    done
fi
