#!/bin/sh
#shortcut git status
#~zach

BASH_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source $BASH_DIR/ks_config.sh
source $BASH_DIR/telhub.sh

if [ ! -d $MAIN_DIR ]; then
    mkdir $MAIN_DIR
fi

cd $CHARTS

## create new helm chart from heartbeat
helm_chart(){
    if [ ! -d $1 ]; then
        cp -r heartbeat-ps-adapter $1
        for file in 'values.yaml' 'Chart.yaml' 'templates/_helpers.tpl' 'templates/ingress.yaml' 'templates/NOTES.txt'
        do
            sed -i "s/heartbeat-ps-adapter/$1/g" $1/${file}.yaml
        done
    fi
}

## update deployment file
deployment(){
    cp heartbeat-ps-adapter/templates/deployment.yaml $1/templates/deployment.yaml
}

if [ "$1" == "all" ]; then
    for s in "${SERVICE[@]}"
    do
        helm_chart $s
    done
elif [ "$1" == "dep" ]; then
    for s in "${SERVICE[@]}"
    do
        deployment $s
    done
else
    select s in "${SERVICE[@]}"
    do
        helm_chart $s
        exit
    done
fi
