#!/bin/sh
#shortcut git status
#~zach

BASH_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

if [ ! -f ${BASH_DIR}/ks_config.sh ]; then
    cp ${BASH_DIR}/ks_config.sh.sample ${BASH_DIR}/ks_config.sh
    echo PATH=\$PATH:${BASH_DIR} >> ~/.profile
    source ~/.profile
fi

source $BASH_DIR/ks_config.sh
source $BASH_DIR/telhub.sh

if [ ! -d $MAIN_DIR ]; then
    mkdir $MAIN_DIR
fi

cd $MAIN_DIR

clone_repo(){
    if [[ $1 =~ 'telhub-db|elasticmq' ]]; then
        git clone git@github.com:ChisholmZ/${1}.git ${1}
    else
        git clone git@github.com:schneidertech/telematics-hub-${1}.git ${1}
    fi
}

if [ "$1" == "all" ]; then
    for r in "${!REPO_SERVICE[@]}"
    do
        if [ ! -d $r ]; then
            clone_repo $r
        fi
    done
else
    select r in "${!REPO_SERVICE[@]}"
    do
        clone_repo $r
        exit
    done
fi
